/* Juego de preguntas (opciones) - Botanical-online.com - (c) 2016, Daniel Martínez Bou - all rights reserved */
juego.gameTitle=function(a){this.game=a;this._a=null};
juego.gameTitle.prototype={create:function(){this.stage.backgroundColor="#339933";this.game.device.desktop||juego.FULLSCREEN?this._c():(this._a=this.game.add.sprite(this.game.world.width/2,this.game.world.height/2,"clica-movil"),this._a.anchor.setTo(.5),this.game.input.onDown.add(this._d,this))},_b:function(){this.game.add.audio("empezar").play();juego.doCortinilla(this.game,!1,!0).onComplete.add(function(){this.state.start("TheGame")},this)},_c:function(){this.game.add.sprite(this.game.world.width/
2,16,"logo").anchor.setTo(.5,0);var a=this.game.add.text(this.game.world.width/2,this.game.world.height/2,this.game.global.TEXTOS.intro,{font:"30px Arial",fill:"white",align:"center",wordWrap:!0,wordWrapWidth:.9*this.game.world.width});a.setShadow(1,1,"rgba(0,0,0,0.7)",2);a.anchor.setTo(.5,0);a=juego.creaBoton(this.game,this.game.width/2,this.game.height-70,this.game.global.TEXTOS.boton_start,this._b,this);a.y-=a.height/2;new juego.botonResize(this.game);new juego.botonMusica(this.game)},_d:function(){this._a.destroy();
this.game.input.onDown.remove(this._d,this);entrarWidescreen();juego.MODESCREEN=1;this._c()}};juego.creaBoton=function(a,b,e,f,g,h,c){void 0==c&&(c="");var d=a.add.group();d.x=b;d.y=e;d.name=c;b=a.add.button(0,0,"boton",g,h,2,0,1);b.anchor.setTo(.5,.5);b.name=c;a=a.add.text(0,7,f,{font:"bold 22px  Verdana",fill:"white",align:"center"});a.anchor.setTo(.5,.5);d.add(b);d.add(a);return d};
juego._e=function(a,b,e,f,g,h,c){a=a.add.graphics(b,e);a.beginFill(h,1);a.drawRect(0,0,f,g);a.endFill();a.alpha=c;return a};juego.doCortinilla=function(a,b,e){var f=b?0:1;b=juego._e(a,0,0,a.width,a.height,e?0:16777215,b?1:0);a=a.add.tween(b);a.to({alpha:f},500,Phaser.Easing.Linear.None,!0);return a};juego.botonResize=function(a){Phaser.Group.call(this,a);this.game=a;this._f()};juego.botonResize.prototype=Object.create(Phaser.Group.prototype);juego.botonResize.prototype.constructor=juego.botonResize;
juego.botonResize.prototype._f=function(){var a;switch(juego.MODESCREEN){case 2:a="boton_normalscreen";break;case 0:a="boton_widescreen";break;case 1:a="boton_fullscreen"}juego.BOTON_SCREEN=this.game.add.button(10,10,a,this.cambiarPantalla,this,2,0,1);juego.BOTON_SCREEN.anchor.setTo(0,0)};
juego.botonResize.prototype.cambiarPantalla=function(){juego.BOTON_SCREEN.destroy();juego.MODESCREEN=(juego.MODESCREEN+1)%3;this._f();switch(juego.MODESCREEN){case 0:this.game.scale.stopFullScreen();this.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;break;case 1:entrarWidescreen();break;case 2:salirWidescreen(),this.game.scale.startFullScreen(!0),this.game.scale.fullScreenScaleMode=Phaser.ScaleManager.EXACT_FIT}};juego.botonMusica=function(a){Phaser.Group.call(this,a);this.game=a;this._f();this._g()};
juego.botonMusica.prototype=Object.create(Phaser.Group.prototype);juego.botonMusica.prototype.constructor=juego.botonMusica;juego.botonMusica.prototype._f=function(){var a;switch(juego.SONIDO){case "true":a="boton-sonido";break;case "false":a="boton-no-sonido"}null!=juego.BOTON_SONIDO&&juego.BOTON_SONIDO.destroy();juego.BOTON_SONIDO=this.game.add.button(10,80,a,this._h,this,2,0,1);juego.BOTON_SONIDO.anchor.setTo(0,0)};
juego.botonMusica.prototype._h=function(){switch(juego.SONIDO){case "true":juego.SONIDO="false";break;case "false":juego.SONIDO="true"}localStorage.setItem("sonido",juego.SONIDO);this._f();this._g()};juego.botonMusica.prototype._g=function(){switch(juego.SONIDO){case "true":this.game.sound.mute=!1;break;case "false":this.game.sound.mute=!0}};