/* Juego de preguntas (opciones) - Botanical-online.com - (c) 2016, Daniel Martínez Bou - all rights reserved */
juego.theGame=function(a){
  this.game=a;
  this._q=[];
  this._ae=this._c=this._m=this._ah=this._o=this._e=this._h=this._ag=this._af=this._a=null;
  this._p=!1;
  this._i=0};
  juego._g=function(a,c,b,d,h){function e(a,c,b,d,f,g){d%2&&" "!=b[d]&&g.play();c.text+=b[d];d++;d<b.length&&a.time.events.add(f,e,this,a,c,b,d,f,g)}b=b.split("");e(a,c,b,0,d,h);return a.add.tween(this).to({},b.length*d,"Linear",!0)};juego._ac=function(a){for(var c=0,b=0;b<a.length;b++)null!=a[b]&&c++;return c};
juego._b=function(a,c,b){a.time.events.add(c,function(){a.add.audio(b).play()},this)};
juego.theGame.prototype={init:function(){this._i=juego.ACIERTOS=0;this._p=!1;this._ad(this.game.global.PREGUNTAS)},create:function(){new juego.botonResize(this.game);new juego.botonMusica(this.game);var a=this.game.add.button(10,this.game.height-10,"boton_restart",this._aa,this,2,0,1);a.anchor.setTo(0,1);var c=this.game.add.graphics(0,0);c.beginFill(2777642);c.drawRect(this.game.world.width-420-10,10,420,this.game.height-20);c.endFill();this._ae=this.game.add.button(10,a.y-a.height/2,"boton_help",
this._ab,this,2,0,1);this._ae.anchor.setTo(0,.5);this._ae.y-=this._ae.height+10;this._af=null;this._s()},update:function(){},_ad:function(a){for(var c=[],b=0;b<a.length;b++)c.push(b);c=Phaser.ArrayUtils.shuffle(c);this._h=[];for(var d=0;d<c.length;d++)b=c[d],this._h.push(a[b])},_ab:function(){if(null==this._af&&!(3>juego._ac(this._q))){var a,c;do c=this.game.rnd.integerInRange(0,this._q.length-1),a=this._q[c];while(null==a||a._r==this._o);this.game.add.audio("ayuda").play();this._af=this.game.add.tween(a.boton).to({x:a.boton.x-
80},200,Phaser.Easing.Bounce.Out).to({x:this.game.width+a.boton.width+80},1E3,Phaser.Easing.Bounce.Out);this._af.onComplete.add(function(){a.boton.destroy();this._af=this._q[c]=null},this);this._af.start();this._p=!0}},_aa:function(){null!=this._a&&(this._a.destroy(),this._a=null);this.game.add.audio("volver").play();t=juego.doCortinilla(this.game,!1,!0);t.onComplete.add(function(){this.game.state.start("GameTitle")},this)},_d:function(a){null==this._af&&null==this._a&&(a=this._q[a.name],this._o==
a._r?(this.game.add.audio("si").play(),this._p||juego.ACIERTOS++,this._af=!0,this._ag=this.game.add.sprite(a.boton.x+a.boton.width/2,a.boton.y,"tick_anim"),this._ag.anchor.setTo(.5,.5),this._ag.animations.add("_ag"),this._ag.animations.play("_ag",15,!1),this._ag.animations.currentAnim.onComplete.add(function(){this._af=null;this._z()},this)):(this._p=!0,this.game.add.audio("no").play(),this._af=!0,this._af=this.game.add.tween(a.boton).to({x:a.boton.x+6,angle:5},40,Phaser.Easing.Linear.None).to({x:a.boton.x-
6,angle:-5},40,Phaser.Easing.Linear.None).to({x:a.boton.x+6,angle:5},40,Phaser.Easing.Linear.None).to({x:a.boton.x-5,angle:-5},40,Phaser.Easing.Linear.None).to({x:a.boton.x+4,angle:5},40,Phaser.Easing.Linear.None).to({x:a.boton.x-3,angle:-5},40,Phaser.Easing.Linear.None).to({x:a.boton.x+2,angle:5},40,Phaser.Easing.Linear.None).to({x:a.boton.x-1,angle:-5},40,Phaser.Easing.Linear.None).to({x:a.boton.x,angle:0},40,Phaser.Easing.Linear.None),this._af.onComplete.add(function(){this._af=null},this),this._af.start()))},
_z:function(){if(null!=this._a){if("acierto"==this._a.name)return;this._a.destroy()}juego._b(this.game,800,"popup");this._a=this.game.add.sprite(this.game.width/2,this.game.height/2,"acierto");this._a.anchor.setTo(.5,.5);this._a.scale.setTo(.3,.3);this._a.alpha=0;this._a.name="acierto";this.game.add.tween(this._a.scale).to({x:1,y:1},800,Phaser.Easing.Bounce.Out,!0,800);this._af=this.game.add.tween(this._a).to({alpha:1},1E3,Phaser.Easing.Bounce.Out,!0,600);this._af.onComplete.add(this._y,this);this._af.start()},
_y:function(){this.game.time.events.add(1.5*Phaser.Timer.SECOND,function(){this._af=this.game.add.tween(this._a).to({x:this.game.width,alpha:0},800,Phaser.Easing.Sinusoidal.InOut,!0);this._af.onComplete.add(this._x,this);this._af.start()},this)},_x:function(){"acierto"==this._a.name?(this._a.destroy(),this._a=null,this._w()):(this._a.destroy(),this._a=null);this._af=null;this._ag.destroy()},_w:function(){this._i++;this._h.length==this._i?this._v():this._s()},_v:function(){this.game.add.audio("final").play();
this._a=this.game.add.sprite(this.game.width/2,this.game.height/2,"estadisticas");this._a.anchor.setTo(.5,.5);this._a.alpha=0;this._a.scale.setTo(.3,.3);this.game.add.tween(this._a.scale).to({x:1,y:1},1E3,Phaser.Easing.Bounce.Out,!0);this._af=this.game.add.tween(this._a).to({alpha:1},1E3,Phaser.Easing.Bounce.Out,!0);this._af.onComplete.add(this._u,this);this._af.start()},_u:function(){this.game.time.events.add(3*Phaser.Timer.SECOND,function(){this._af=this.game.add.tween(this._a).to({x:this.game.width,
alpha:0},1E3,Phaser.Easing.Sinusoidal.InOut,!0);this._af.onComplete.add(this._t,this);this._af.start()},this)},_t:function(){this._af=juego.doCortinilla(this.game,!1,!0);this._af.onComplete.add(function(){this.game.state.start("GameOver")},this)},_s:function(){void 0!=this._ah&&(this._ah.destroy(),this._ah=null);void 0!=this._m&&(this._m.destroy(),this._m=null);void 0!=this._c&&(this._c.destroy(),this._c=null);if(this._q.length){for(var a=0;a<this._q.length;a++)null!=this._q[a]&&this._q[a].boton.destroy();
this._q=[]}this._e=Phaser.ArrayUtils.shuffle(this._h[this._i].opciones);this._o=this._h[this._i].correcta;this._p=!1;juego._b(this.game,0,"slider");juego.doCortinilla(this.game,!0,!0);this._n()},_n:function(){this._ah=this.game.add.sprite(this.game.width,this.game.height-10,this._h[this._i].grafico);this._ah.anchor.setTo(0,1);this._af=this.game.add.tween(this._ah).to({x:90},500,Phaser.Easing.Back.Out,!0,300);this._af.onComplete.add(function(){this.game.time.events.add(700,function(){this._l();this._k()},
this)},this)},_l:function(){null!=this._h[this._i].reflejo&&(this._m=this.game.add.sprite(90,this.game.height-10,this._h[this._i].reflejo),this._m.anchor.setTo(0,1),this._m.alpha=0,this.game.add.tween(this._m).to({alpha:.9},200,Phaser.Easing.Linear.None,!0,0,9999,!0))},_k:function(){var a=this._h[this._i].enunciado;this._c=this.game.add.text(this.game.world.width-420-10+10,30,"",{font:"bold 30px Arial",fill:"white",wordWrap:!0,wordWrapWidth:420});this._c.anchor.setTo(0,0);var c=this.game.add.audio("tecla");
this.game.add.audio("tecla-salto");this._af=juego._g(this.game,this._c,a,30,c);this._af.onComplete.add(function(){this._f()},this)},_f:function(){for(var a=0;a<this._e.length;a++){var c=this._e[a],b=juego.creaBoton(this.game,0,0,c,this._d,this,a);b.x=this.game.width+b.width;b.y=this._c.height+this._c.y+b.height/2+50+(b.height+20)*a;var d=this.game.world.width-420+105-10+b.width/2;this.game.add.tween(b).to({x:d},800,Phaser.Easing.Bounce.Out,!0,600*a+300);this._q.push({boton:b,_r:c});juego._b(this.game,
600*a+400,"opcion")}this._a=this._af=null}};